const specialProducts = [
  {
    id: 1,
    img: "/img/product/sp1.webp",
    caption: " پاور بانک 3000 سیلیکون پاور",
    price: "780,000",
    offPrice: "945,000",
    isSpecial: true,
    off: 15,
    fastDeliver: true,
    color: ["red"],
    rate: 1,
    pcomment: ["خوب", "بد", "عالی", "بیست"],
  },
  {
    id: 2,
    img: "/img/product/sp2.webp",
    caption: "ساعت هوشمند هاینوتکو مدل (H45 Pro Max (Series 8",
    price: "779,900",
    offPrice: "936,000",
    isSpecial: true,
    off: 15,
    fastDeliver: true,
    color: ["black"],
    rate: 4,
    pcomment: [],
  },
  {
    id: 3,
    img: "/img/product/sp4.webp",
    caption: "ساعت هوشمند تلزیل مدل T-FLY",
    price: "2,209,000",
    offPrice: "2,417,000",
    isSpecial: true,
    off: 7,
    fastDeliver: true,
    color: ["black", "silver"],
    rate: 5,
    pcomment: ["خوب", "بد", "زشت"],
  },
  {
    id: 4,
    img: "/img/product/sp5.webp",
    caption: "هندزفری سیمی سامسونگ مدل EO-IA500",
    price: "389,000",
    offPrice: "544,000",
    isSpecial: true,
    off: 8,
    fastDeliver: true,
    color: ["black", "silver"],
    rate: 4,
    pcomment: [],
  },
  {
    id: 5,
    img: "/img/product/sp6.webp",
    caption: "هندزفری بی سیم کیو سی وای مدل ArcBuds Lite",
    price: "900000",
    offPrice: "990000",
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["black"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 6,
    img: "/img/product/sp7.webp",
    caption:
      "شارژر همراه سامسونگ مدل Battery Pack 25W EB-P3300 ظرفیت 10000 میلی آمپر ساعت",
    price: "1,850,000",
    offPrice: "1,942,500",
    isSpecial: true,
    off: 5,
    fastDeliver: true,
    color: ["silver"],
    rate: 2,
    pcomment: ["خوب"],
  },
  {
    id: 7,
    img: "/img/product/sp3.webp",
    caption:
      "گوشی موبایل آنر مدل X6a دو سیم کارت ظرفیت 128 گیگابایت و 4 گیگابایت رم",
    price: "4,825,000",
    offPrice: "5,199,000",
    isSpecial: true,
    off: 7,
    fastDeliver: true,
    color: ["green"],
    rate: 0,
    pcomment: [],
  },
];

const newProducts = [{}];
const topProducts = [{}];
const newPhones = [{}];

export { specialProducts, newProducts, topProducts, newPhones };
