const specialProducts = [
  {
    id: 1,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 2,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 3,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 4,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 5,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 6,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
  {
    id: 7,
    img: "/public/img/sp",
    caption: "این کپشن است برای محصول",
    price: 1000000,
    offPrice: 900000,
    isSpecial: true,
    off: 10,
    fastDeliver: true,
    color: ["red"],
    rate: 4,
    pcomment: ["خوب", "بد"],
  },
];

const newProducts = [{}];
const topProducts = [{}];
const newPhones = [{}];

export { specialProducts, newProducts, topProducts, newPhones };
